/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "helloworld_constants.h"



const helloworldConstants g_helloworld_constants;

helloworldConstants::helloworldConstants() {
}



