/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef helloworld_CONSTANTS_H
#define helloworld_CONSTANTS_H

#include "helloworld_types.h"



class helloworldConstants {
 public:
  helloworldConstants();

};

extern const helloworldConstants g_helloworld_constants;



#endif
